"""
CodeBuilderAgent — builds agent code from build specs.

Handles:
    (agent_build, build_agent_code)

Stage 2:
- accepts build spec
- returns ready-to-write files payload
- payload is compatible with GitHubWriterAgent
"""

import logging
import re

from services.storage.models.task import TaskModel
from services.execution.result  import ExecutionResult
from agents.base.base_agent import BaseAgent

log = logging.getLogger(__name__)

_HANDLED = {
    ("agent_build", "build_agent_code"),
}


class CodeBuilderAgent(BaseAgent):
    agent_id = "builtin_code_builder_agent_v3"
    name = "Code Builder Agent"
    department = "executive"
    version = 3

    def can_handle(self, task_type: str, action: str) -> bool:
        return (task_type, action) in _HANDLED

    def execute(self, task: TaskModel) -> ExecutionResult:
        try:
            return self._run(task)
        except Exception as e:
            log.error(f"[CodeBuilderAgent] error task={task.id}: {e}", exc_info=True)
            return ExecutionResult(
                success=False,
                message=f"שגיאה בבניית קוד: {e}",
                output={"error": str(e)},
            )

    def _run(self, task: TaskModel) -> ExecutionResult:
        params = self._input_params(task)
        command = (task.input_data or {}).get("command", "").strip()

        display_name = (
            params.get("agent_name")
            or params.get("requested_agent")
            or "Executive Assistant Agent"
        ).strip()

        file_name = self._safe_file_name(display_name)
        class_name = self._safe_class_name(display_name)
        file_path = f"agents/departments/executive/{file_name}.py"

        code = self._build_agent_code(display_name, class_name, file_name)

        files = [
            {
                "path": file_path,
                "content": code,
            }
        ]

        return ExecutionResult(
            success=True,
            message=f"קוד סוכן מוכן עבור {display_name}",
            output={
                "requested_agent": display_name,
                "goal": command or "בניית קוד לסוכן חדש",
                "status": "code_ready",
                "next_step": "apply_files_to_github",
                "commit_message": f"Add {class_name} via AshbalOS",
                "files": files,
                "count": len(files),
                "register_in": "agents/base/agent_registry.py",
            },
        )

    def _build_agent_code(self, display_name: str, class_name: str, file_name: str) -> str:
        return f'''"""
{class_name} — generated by CodeBuilderAgent.
"""

import logging

from services.storage.models.task import TaskModel
from services.execution.result  import ExecutionResult
from agents.base.base_agent import BaseAgent

log = logging.getLogger(__name__)

_HANDLED = {{
    ("assistant", "plan_action"),
}}


class {class_name}(BaseAgent):
    agent_id = "builtin_{file_name}_v1"
    name = "{display_name}"
    department = "executive"
    version = 1

    def can_handle(self, task_type: str, action: str) -> bool:
        return (task_type, action) in _HANDLED

    def execute(self, task: TaskModel) -> ExecutionResult:
        try:
            command = (task.input_data or {{}}).get("command", "").strip()
            return ExecutionResult(
                success=True,
                message="{display_name} קיבל את הבקשה",
                output={{
                    "agent": "{display_name}",
                    "status": "received",
                    "task_type": task.type,
                    "action": task.action,
                    "command": command,
                }},
            )
        except Exception as e:
            log.error(f"[{class_name}] error task={{task.id}}: {{e}}", exc_info=True)
            return ExecutionResult(
                success=False,
                message=f"שגיאה בסוכן {display_name}: {{e}}",
                output={{"error": str(e)}},
            )
'''

    def _safe_file_name(self, text: str) -> str:
        ascii_name = re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_").lower()
        if ascii_name:
            return ascii_name

        if "מכירות" in text:
            return "sales_assistant_agent"
        if "אישי" in text or "עוזר" in text:
            return "executive_assistant_agent"

        return "generated_agent"

    def _safe_class_name(self, text: str) -> str:
        ascii_parts = re.findall(r"[A-Za-z0-9]+", text)
        if ascii_parts:
            return "".join(p[:1].upper() + p[1:] for p in ascii_parts)

        if "מכירות" in text:
            return "SalesAssistantAgent"
        if "אישי" in text or "עוזר" in text:
            return "ExecutiveAssistantAgent"

        return "GeneratedAgent"
