"""
SalesAssistantAgent — generated by CodeBuilderAgent.
"""

import logging

from services.storage.models.task import TaskModel
from services.execution.result  import ExecutionResult
from agents.base.base_agent import BaseAgent

log = logging.getLogger(__name__)

_HANDLED = {
    ("assistant", "plan_action"),
}


class SalesAssistantAgent(BaseAgent):
    agent_id = "builtin_sales_assistant_agent_v1"
    name = "עוזר מכירות"
    department = "executive"
    version = 1

    def can_handle(self, task_type: str, action: str) -> bool:
        return (task_type, action) in _HANDLED

    def execute(self, task: TaskModel) -> ExecutionResult:
        try:
            command = (task.input_data or {}).get("command", "").strip()
            return ExecutionResult(
                success=True,
                message="עוזר מכירות קיבל את הבקשה",
                output={
                    "agent": "עוזר מכירות",
                    "status": "received",
                    "task_type": task.type,
                    "action": task.action,
                    "command": command,
                },
            )
        except Exception as e:
            log.error(f"[SalesAssistantAgent] error task={task.id}: {e}", exc_info=True)
            return ExecutionResult(
                success=False,
                message=f"שגיאה בסוכן עוזר מכירות: {e}",
                output={"error": str(e)},
            )
